#!/usr/bin/expect

#Definicion de variables. 

set timeout 10
set servidor "bandit.labs.overthewire.org"
set puerto 2220
set usuario "bandit0"
set contrasena "bandit0"


#Iniciar la sesión en el SSH

spawn ssh -p $puerto $usuario@$servidor

#Esperar el prompt de la contrasena
expect "password:"

#Enviar la contrasena
send "$contrasena\r"

#Esperar el prompt del shell
expect "$ "

#Comando para leer la contraseña del archivo readme.
send "cat readme\r"

#Capturar la contraseña 
expect -re "(.*)\r"
set siguiente_contrasena $expect_out(1,string)

#Cerrar la sesión del SSH
send "exit\r"
expect eof
