#!/bin/bash

#Declaración de variables
user="bandit3"
host="bandit.labs.overthewire.org"
port=2220
password="MNk8KNH3Usiio41PRUEoDFPqfxLPlSmx"

#Comandos necesarios para ejecutar en el server remoto
commands="
cd ~;
cd inhere
cat ...Hiding-From-You
"

#Usar el sshpass para conectar y ejecutar los comandos.
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p $port $user@$host "$commands"
